name: 🚀 機能追加・改善 (Feature Request)
description: 新しい機能の追加や既存機能の改善を提案します。
title: "[Feature]: "
labels: ["enhancement", "feature"]
assignees:
  - # ここにデフォルトの担当者名 (オプション)

body:
  - type: markdown
    attributes:
      value: |
        ### はじめに
        このIssueは、GitHub ActionsパイプラインにDocker関連機能を追加する要望に対応するためのものです。

  - type: textarea
    id: overview
    attributes:
      label: 🚀 概要 (Overview)
      description: 本Issueの目的と達成したい結果を簡潔に記述してください。
      placeholder: |
        - Github Actionsのパイプラインに機能を追加する
        - mainブランチにマージした際に、Dockerイメージをビルドし、Registryにpushする
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 💡 詳細 (Details)
      description: 具体的な作業内容、背景、満たすべき要件を記述してください。
      placeholder: |
        ## .dockerignore の追加
        - 目的: 不要な設定ファイルなどが意図せず混入されるのを防ぐ。
        - 要件: .gitignoreの内容を参考に、適切な.dockerignoreを作成する。
        
        ## Github Actionsのパイプライン修正
        - 対象ファイル: ci.yml
        - 目的: CIパイプラインにDockerイメージのビルドとRegistryへのプッシュ機能を追加する。
        - 要件:
          1. mainブランチへのマージ時に、Dockerイメージをビルドすること。
          2. ビルドしたDockerイメージを以下の2箇所にプッシュすること:
             - Github Registry
             - DockerHub
    validations:
      required: true

  - type: textarea
    id: assumptions
    attributes:
      label: 📘 前提 (Assumptions)
      description: この作業を実施する上で必須となる条件を記述してください。
      value: |
        - 適切な作業ブランチを作成すること
        - `概要` `詳細` の内容を読み取り、記述内容の条件を全て対応すること
        - `gh`コマンドを利用し、Pull Requestを作成すること
          - Pull Request内の言語は日本語で記述すること
          - Pull Requestには変更内容に応じて処理シーケンスなどを `mermaid` 形式で記述すること
        - GEMINIが変更内容を適切にトレースできるよう、必要に応じて `GEMINI.md` を修正すること
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ タスクリスト (Checklist)
      description: 実施すべき具体的な作業項目をチェックリスト形式で確認します。
      options:
        - label: 適切な作業ブランチを作成
          required: true
        - label: `.dockerignore` ファイルを追加し、適切な除外設定を記述
          required: true
        - label: このIssue内に記載の「前提」「概要」「詳細」を満たす全ての機能を実装すること
          required: true
        - label: 必要に応じて `GEMINI.md` を修正
          required: true
        - label: `gh` コマンドを利用してPull Requestを作成 (日本語、`mermaid`形式のシーケンス図を記載)
          required: true

  - type: input
    id: additional_notes
    attributes:
      label: 📝 その他特記事項 (Additional Notes)
      description: その他、関連情報や懸念点などがあれば記述してください。
    validations:
      required: false