name: 🐛 バグ報告 (Bug Report)
description: 期待通りに動作しない問題やエラーを報告します。
title: "[Bug]: "
labels: ["bug"]
assignees:
  - eddie-splatoon

body:
  - type: textarea
    id: assumptions
    attributes:
      label: 📘 前提 (Assumptions)
      description: コーディングエージェントが実行すべき作業の前提条件を記載してください。
      value: |
        - Issueに対応する適切な作業ブランチを作成すること
        - `概要` `詳細` の内容を読み取り、記述内容の条件を全て対応すること
        - コード修正時、対応するテストも必ず作成すること
        - ESLintによるチェックを実行すること
        - `gh`コマンドを利用し、Pull Requestを作成すること
          - Pull Request内の言語は日本語で記述すること
          - Pull Requestには変更内容に応じて処理シーケンスなどを `mermaid` 形式で記述すること
          - 指定されたIssue番号を記述すること
        - GEMINIが変更内容を適切にトレースできるよう、必要に応じて `GEMINI.md` を修正すること
    validations:
      required: true

  - type: textarea
    id: overview
    attributes:
      label: 🐛 概要 (Overview)
      description: 発生しているバグの概要を簡潔に記述してください。
      placeholder: |
        例:
        - 特定の操作をすると、アプリケーションがクラッシュする
        - 計算結果が期待される値と異なる
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 再現手順 (Steps to Reproduce)
      description: バグを再現させるための具体的な手順を記述してください。
      placeholder: |
        例:
        1. '...' に移動する
        2. '....' をクリックする
        3. '....' までスクロールする
        4. エラーが発生する
    validations:
      required: true
  
  - type: textarea
    id: expected-behavior
    attributes:
      label: 期待される動作 (Expected Behavior)
      description: 本来であれば、どのような動作になるべきかを記述してください。
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: 実際の動作 (Actual Behavior)
      description: 実際にどのような動作になっているかを記述してください。
    validations:
      required: true

  - type: input
    id: additional_notes
    attributes:
      label: 📝 その他特記事項 (Additional Notes)
      description: その他、関連情報やスクリーンショット、エラーログなどがあれば記述してください。
    validations:
      required: false
